# Data Ingestion.
In this notebook, data is fetched from yfinance api and returned as a pandas dataframe. The tickers, start date, end date are from the config file. This can be changed as long as the available tickers and time are present on yfinance api.

This notebook aims to show how data ingestion can be done with this current repository structure.

In [1]:
#!pip install -qqq yfinance pandas pyportfolioopt

# All Prices
These prices are the closing prices of the asset.
All Prices include the following asset classes: stocks, cryptocurrencies, etfs. bonds and SP500 index.
More asset classes can be added, however, this is the data in the current config file.
This first section will show how all prices from config are loaded at once into a single dataframe.

In [3]:
from portfolio.data.data_ingestion import DataIngestion

obj = DataIngestion()

all_prices = obj.get_all_prices()
all_prices.tail(20)

[*********************100%***********************]  121 of 121 completed

Ticker,AAL,ABEV,ADA-USD,AMD,AMDL,AMUU,AMZN,APLD,APLX,ARMG,...,WULF,WULX,XRP-USD,ZCSH,ZEC-USD,^FVX,^GSPC,^IRX,^TNX,^TYX
Date,,,,,,,,,,,,,,,,,,,,,
2026-03-13,10.30,2.86,0.265694,193.389999,11.26,39.209248,207.669998,27.049999,15.340000,5.959,...,14.670000,20.660000,1.398908,17.070000,207.991348,3.874,6632.189941,3.603,4.285,4.908
2026-03-16,10.49,2.90,0.290380,196.580002,11.63,40.599983,211.740005,27.709999,16.100000,6.580,...,16.410000,25.950001,1.543565,20.190001,278.428986,3.803,6699.379883,3.605,4.220,4.859
2026-03-17,10.86,2.90,0.289063,196.309998,11.61,40.465683,215.199997,27.510000,15.830000,7.190,...,16.040001,24.559999,1.518544,22.011999,271.901459,3.786,6716.089844,3.605,4.202,4.852
2026-03-18,10.80,2.83,0.274191,199.460007,11.96,41.824589,209.869995,26.650000,14.840000,7.310,...,15.300000,22.240000,1.463854,19.040001,248.767258,3.862,6624.700195,3.610,4.259,4.881
2026-03-19,10.80,2.80,0.267356,205.270004,12.65,44.196201,208.759995,26.700001,14.900000,7.460,...,15.740000,23.360001,1.447323,18.299999,234.962189,3.919,6606.490234,3.612,4.281,4.852
2026-03-20,10.43,2.71,0.266119,201.330002,12.19,42.409534,205.369995,25.930000,13.980000,7.770,...,15.100000,21.620001,1.445461,17.150000,234.582443,4.012,6506.479980,3.618,4.391,4.960
2026-03-23,10.81,2.80,0.261601,202.679993,12.32,43.086002,210.139999,27.260000,15.400000,8.270,...,16.190001,24.629999,1.431878,18.174999,228.458237,3.950,6581.000000,3.612,4.334,4.912
2026-03-24,10.71,2.78,0.266189,205.369995,12.65,44.063999,207.240005,26.790001,14.910000,8.060,...,16.219999,24.770000,1.415424,18.020000,242.257889,4.030,6556.370117,3.620,4.392,4.941
2026-03-25,10.74,2.85,0.270307,220.270004,14.46,50.501999,211.710007,28.370001,16.610001,10.680,...,16.860001,26.610001,1.414238,18.500000,231.362701,3.970,6591.899902,3.620,4.328,4.897
2026-03-26,10.71,2.82,0.254774,203.770004,12.33,42.980999,207.539993,25.715000,13.530000,10.350,...,15.350000,21.959999,1.360114,18.003000,222.072952,4.095,6477.160156,3.620,4.416,4.936
2026-03-27,10.30,2.81,0.246024,201.990005,12.09,42.212002,199.339996,23.760000,11.420000,8.930,...,14.890000,20.680000,1.325014,16.797001,215.344910,4.070,6368.850098,3.607,4.440,4.982
2026-03-30,10.18,2.82,0.243194,196.039993,11.36,39.682999,200.949997,20.545000,8.340000,8.040,...,13.700000,17.320000,1.322583,17.690001,225.563431,3.979,6343.720215,3.598,4.342,4.905
2026-03-31,10.74,2.92,0.241563,203.429993,12.21,42.591000,208.270004,23.740000,10.930000,9.710,...,14.430000,19.120001,1.340259,20.669001,248.493561,3.945,6528.520020,3.600,4.311,4.891
2026-04-01,11.13,2.97,0.248058,210.210007,13.04,45.459000,210.570007,24.490000,11.600000,10.200,...,14.480000,19.219999,1.347766,20.299999,251.070862,3.955,6575.319824,3.605,4.319,4.900
2026-04-02,10.84,2.93,0.239358,217.500000,13.93,48.509998,209.770004,24.559999,11.660000,9.400,...,14.880000,20.350000,1.318691,21.719999,240.852753,3.948,6582.689941,3.607,4.313,4.890
2026-04-06,10.90,2.99,0.246090,220.179993,14.27,49.719002,212.789993,25.190001,12.240000,9.370,...,15.550000,22.080000,1.321221,21.364000,251.550964,3.981,6611.830078,3.623,4.335,4.891
2026-04-07,10.81,2.97,0.263792,221.529999,14.42,50.205002,213.770004,25.180000,12.200000,8.750,...,16.570000,24.770000,1.381490,22.198000,319.656891,3.976,6616.850098,3.615,4.343,4.921

## Asset Classes loaded individually.
Stock, Crypto, ETF, Bonds, and SP500 index closing prices can be loaded individually in this section.
Note: Every time this is loaded from yfinance, it will be fetched from the api. If you want to save these files to a CSV or cache these files, it is recommended.

In [4]:
# use instance of DataIngestion to fetch stock prices.

stock_prices = obj.get_stock_prices()
stock_prices.tail(10)

[*********************100%***********************]  54 of 54 completed

Ticker,AAL,ABEV,AMD,AMZN,APLD,BB,BBD,BMNR,CCL,CIFR,...,SNAP,SOFI,STLA,T,TGT,TSLA,VG,VZ,WMT,WULF
Date,,,,,,,,,,,,,,,,,,,,,
2026-03-24,10.71,2.78,205.369995,207.240005,26.790001,3.23,3.491638,20.799999,25.469999,14.880,...,4.36,16.700001,6.75,28.570974,115.919998,383.029999,16.600000,50.155621,122.050003,16.219999
2026-03-25,10.74,2.85,220.270004,211.710007,28.370001,3.29,3.599830,21.240000,25.730000,15.880,...,4.49,16.559999,6.88,28.511595,116.370003,385.950012,16.709999,49.623623,123.059998,16.860001
2026-03-26,10.71,2.82,203.770004,207.539993,25.715000,3.25,3.481802,19.469999,25.280001,14.350,...,4.01,15.870000,6.75,28.620457,117.000000,372.109985,16.820000,49.988140,122.180000,15.350000
2026-03-27,10.30,2.81,201.990005,199.339996,23.760000,3.16,3.432625,18.389999,24.190001,13.745,...,3.93,15.230000,6.71,28.798592,119.839996,361.829987,17.530001,49.564514,122.889999,14.890000
2026-03-30,10.18,2.82,196.039993,200.949997,20.545000,3.15,3.442460,18.299999,23.959999,12.015,...,4.02,15.150000,6.75,28.481907,118.779999,355.279999,16.889999,49.554661,123.500000,13.700000
2026-03-31,10.74,2.92,203.429993,208.270004,23.740000,3.24,3.589994,19.780001,25.879999,12.870,...,4.60,15.880000,7.09,28.689732,121.199997,371.750000,15.760000,49.456142,124.279999,14.430000
2026-04-01,11.13,2.97,210.210007,210.570007,24.490000,3.36,3.668679,19.690001,26.580000,12.640,...,4.90,15.630000,7.43,28.016773,120.449997,381.260010,14.680000,48.658142,124.739998,14.480000
2026-04-02,10.84,2.93,217.500000,209.770004,24.559999,3.46,3.599830,19.450001,25.639999,12.820,...,4.63,15.850000,7.55,28.036568,120.449997,360.589996,14.640000,48.667999,125.790001,14.880000
2026-04-06,10.90,2.99,220.179993,212.789993,25.190001,3.55,3.662846,20.600000,25.969999,13.350,...,4.71,16.270000,7.48,28.026670,122.209999,352.820007,15.940000,48.421703,126.790001,15.550000
2026-04-07,10.81,2.97,221.529999,213.770004,25.180000,3.48,3.653000,20.170000,25.200001,14.010,...,4.80,16.110001,7.42,27.749571,119.519997,346.649994,15.990000,47.899551,122.489998,16.570000

In [5]:
# use instance of DataIngestion to fetch etf prices.

etf_prices = obj.get_etf_prices()
etf_prices.tail(10)

[*********************100%***********************]  36 of 36 completed

Ticker,AMDL,AMUU,APLX,ARMG,AVGG,AVGU,AVGX,AVL,BEG,CIFU,...,QQQ,QUBX,SMCL,TEMT,USAX,USGG,VFPAF,VOYX,WULX,ZCSH
Date,,,,,,,,,,,,,,,,,,,,,
2026-03-27,12.09,42.212002,11.42,8.93,19.280001,24.778000,33.189999,31.170000,23.749001,14.040000,...,562.580017,7.24,1.600,15.920000,13.78,8.411,46.027000,8.560,20.680000,16.797001
2026-03-30,11.36,39.682999,8.34,8.04,18.330000,23.521000,31.510000,29.680000,18.785999,10.540000,...,558.280029,6.48,1.470,15.620000,11.57,7.115,45.132999,7.847,17.320000,17.690001
2026-03-31,12.21,42.591000,10.93,9.71,20.320000,26.035000,34.990002,32.879002,23.652000,11.860000,...,577.179993,7.50,1.720,17.799999,13.09,7.955,45.132999,8.750,19.120001,20.669001
2026-04-01,13.04,45.459000,11.60,10.20,20.829000,26.735001,35.849998,33.757999,22.774000,11.620000,...,584.309998,7.20,1.670,19.200001,12.44,7.615,45.132999,9.050,19.219999,20.299999
2026-04-02,13.93,48.509998,11.66,9.40,20.930000,26.830000,36.029999,33.939999,23.680000,11.940000,...,584.979980,7.53,1.770,19.340000,14.43,8.750,45.132999,11.410,20.350000,21.719999
2026-04-06,14.27,49.719002,12.24,9.37,20.914000,26.799999,36.040001,33.939999,23.405001,12.830000,...,588.500000,7.50,1.595,19.400000,13.14,8.070,45.132999,12.280,22.080000,21.364000
2026-04-07,14.42,50.205002,12.20,8.75,23.469999,30.087000,40.450001,38.090000,23.844999,14.060000,...,588.590027,7.30,1.680,18.850000,12.11,7.346,45.132999,11.930,24.770000,22.198000
2026-04-08,15.77,54.959999,14.71,9.33,25.790001,33.104000,44.430000,41.790001,27.601999,16.930000,...,606.090027,7.70,1.790,19.590000,15.51,9.474,50.075001,12.630,29.180000,27.000000
2026-04-09,16.40,57.178001,12.35,9.44,26.459999,33.994999,45.619999,42.959999,32.486000,19.129999,...,610.190002,7.39,1.750,16.809999,15.56,9.465,50.224998,13.960,32.599998,29.150000
2026-04-10,17.57,61.250999,12.97,9.34,28.920000,37.279999,49.860001,46.919998,35.008999,19.240000,...,611.070007,7.95,2.070,15.900000,14.57,8.785,50.224998,14.140,32.139999,30.200001

## Returns
The returns of all assets can be returned using the instance of DataIngestion.

In [6]:
all_returns = obj.compute_returns(stock_prices)
all_returns.tail(10)

Ticker,AAL,ABEV,AMD,AMZN,APLD,BB,BBD,BMNR,CCL,CIFR,...,SNAP,SOFI,STLA,T,TGT,TSLA,VG,VZ,WMT,WULF
Date,,,,,,,,,,,,,,,,,,,,,
2026-03-24,-0.009251,-0.007143,0.013272,-0.013800,-0.017241,-0.027108,-0.011142,-0.022097,0.000786,-0.000672,...,-0.033259,-0.026239,0.024279,0.003825,0.008614,0.005724,0.050633,0.006524,0.011017,0.001853
2026-03-25,0.002801,0.025180,0.072552,0.021569,0.058977,0.018576,0.030986,0.021154,0.010208,0.067204,...,0.029816,-0.008383,0.019259,-0.002078,0.003882,0.007623,0.006626,-0.010607,0.008275,0.039458
2026-03-26,-0.002793,-0.010526,-0.074908,-0.019697,-0.093585,-0.012158,-0.032787,-0.083333,-0.017489,-0.096348,...,-0.106904,-0.041667,-0.018895,0.003818,0.005414,-0.035860,0.006583,0.007346,-0.007151,-0.089561
2026-03-27,-0.038282,-0.003546,-0.008735,-0.039510,-0.076026,-0.027692,-0.014124,-0.055470,-0.043117,-0.042160,...,-0.019950,-0.040328,-0.005926,0.006224,0.024273,-0.027626,0.042212,-0.008475,0.005811,-0.029967
2026-03-30,-0.011650,0.003559,-0.029457,0.008077,-0.135311,-0.003165,0.002865,-0.004894,-0.009508,-0.125864,...,0.022901,-0.005253,0.005961,-0.010997,-0.008845,-0.018102,-0.036509,-0.000199,0.004964,-0.079919
2026-03-31,0.055010,0.035461,0.037696,0.036427,0.155512,0.028571,0.042857,0.080874,0.080134,0.071161,...,0.144279,0.048185,0.050370,0.007297,0.020374,0.046358,-0.066903,-0.001988,0.006316,0.053285
2026-04-01,0.036313,0.017123,0.033328,0.011043,0.031592,0.037037,0.021918,-0.004550,0.027048,-0.017871,...,0.065217,-0.015743,0.047955,-0.023456,-0.006188,0.025582,-0.068528,-0.016136,0.003701,0.003465
2026-04-02,-0.026056,-0.013468,0.034680,-0.003799,0.002858,0.029762,-0.018767,-0.012189,-0.035365,0.014240,...,-0.055102,0.014076,0.016151,0.000707,0.000000,-0.054215,-0.002725,0.000203,0.008418,0.027624
2026-04-06,0.005535,0.020478,0.012322,0.014397,0.025652,0.026012,0.017505,0.059126,0.012871,0.041342,...,0.017279,0.026498,-0.009272,-0.000353,0.014612,-0.021548,0.088798,-0.005061,0.007950,0.045027
2026-04-07,-0.008257,-0.006689,0.006131,0.004606,-0.000397,-0.019718,-0.002688,-0.020874,-0.029650,0.049438,...,0.019108,-0.009834,-0.008021,-0.009887,-0.022011,-0.017488,0.003137,-0.010783,-0.033914,0.065595

In [7]:
# example of returns for bonds

bond_returns = obj.compute_returns(prices=obj.get_bond_prices())
bond_returns.tail(10)

[*********************100%***********************]  4 of 4 completed

Ticker          ^FVX      ^IRX      ^TNX      ^TYX
Date
2026-03-27 -0.006105 -0.003591  0.005435  0.009319
2026-03-30 -0.022359 -0.002495 -0.022072 -0.015456
2026-03-31 -0.008545  0.000556 -0.007140 -0.002854
2026-04-01  0.002535  0.001389  0.001856  0.001840
2026-04-02 -0.001770  0.000555 -0.001389 -0.002041
2026-04-06  0.008359  0.004436  0.005101  0.000204
2026-04-07 -0.001256 -0.002208  0.001845  0.006134
2026-04-08 -0.014085 -0.004149 -0.011973 -0.006909
2026-04-09 -0.001276 -0.003333  0.000466  0.002046
2026-04-10  0.006130  0.001393  0.005590  0.003472